// Generated by [optioner] command-line tool; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

// Copyright 2023 chenmingyong0423

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package log

import (
	"bytes"
	"io"
	"log/slog"
	"time"

	"github.com/chenmingyong0423/ginx/internal/types"
	"github.com/gin-gonic/gin"
)

// RequestLogger 用于打印每个请求的详细信息
// 默认使用 slog 库提供的默认实例进行打印，也可以传入一个 logger 实例
func RequestLogger(opt types.LoggerConfig) gin.HandlerFunc {
	var logger *slog.Logger
	if opt.OptionalLogger != nil {
		logger = opt.OptionalLogger
	} else {
		logger = slog.Default()
	}
	var skip map[string]struct{}

	notLogged := opt.SkipPaths

	if length := len(notLogged); length > 0 {
		skip = make(map[string]struct{}, length)
		for _, path := range notLogged {
			skip[path] = struct{}{}
		}
	}
	return func(ctx *gin.Context) {
		start := time.Now()
		rid := ctx.GetHeader(types.XRequestIDKey)
		path := ctx.Request.URL.Path
		if _, ok := skip[path]; !ok {
			logRequest(ctx, logger, opt.Level, rid)
		}
		mr := &types.Response{
			Body:           bytes.NewBufferString(""),
			ResponseWriter: ctx.Writer,
		}
		ctx.Writer = mr

		ctx.Next()

		if _, ok := skip[path]; !ok && (opt.SkipFunc == nil || !opt.SkipFunc(ctx)) {
			logResponse(ctx, start, logger, opt.Level, mr.Body.String(), rid)
		}
	}
}

func logRequest(ctx *gin.Context, logger *slog.Logger, level slog.Level, rid string) {
	method := ctx.Request.Method
	path := ctx.Request.URL.Path
	query := ctx.Request.URL.RawQuery
	body, _ := ctx.GetRawData()
	ctx.Request.Body = io.NopCloser(bytes.NewBuffer(body))
	logger.Log(ctx, level, "REQUEST", "Uri", path, "Query", query, "Method", method, "Body", string(body), "IP", ctx.ClientIP(), types.XRequestIDKey, rid)
}

func logResponse(ctx *gin.Context, start time.Time, logger *slog.Logger, level slog.Level, body string, rid string) {
	elapsedTime := time.Since(start)
	statusCode := ctx.Writer.Status()
	logger.Log(ctx, level, "RESPONSE", "Code", statusCode, "Body", body, "ElapseTime", elapsedTime, types.XRequestIDKey, rid)
}

type LoggerConfigOption func(config *types.LoggerConfig)

func NewLoggerConfig(level slog.Level, opts ...LoggerConfigOption) *types.LoggerConfig {
	loggerConfig := &types.LoggerConfig{
		Level: level,
	}

	for _, opt := range opts {
		opt(loggerConfig)
	}

	return loggerConfig
}

func WithOptionalLogger(optionalLogger *slog.Logger) LoggerConfigOption {
	return func(loggerConfig *types.LoggerConfig) {
		loggerConfig.OptionalLogger = optionalLogger
	}
}

func WithSkipPaths(skipPaths []string) LoggerConfigOption {
	return func(loggerConfig *types.LoggerConfig) {
		loggerConfig.SkipPaths = skipPaths
	}
}
